### ISSUE TITLE
Failure to deploy when importing dotenv

### ISSUE THREAD

**Issue by Sephster** [netlify/netlify-plugin-gatsby#135]
**Describe the bug**

My site deployed fine when using the old, now deprecated, Gatsby cache Netlify plugin. I uninstalled this plugin and installed the essential gatsby plugin but my build no longer succeeds.

I suspect it is because I am using ES Modules instead of CommonJS. I am importing dotenv in my gatsby-config.js file and when building, I receive the following error:

> Plugin "@netlify/plugin-gatsby" failed

> /opt/build/repo/gatsby-config.js:1
import dotenv from 'dotenv';
^^^^^^

> SyntaxError: Cannot use import statement outside a module

> In "onPreBuild" event in "@netlify/plugin-gatsby" from Netlify app
at loadGatsbyFile (/.netlify/plugins/node_modules/@netlify/plugin-gatsby/src/index.js:32:12)
at onPreBuild (/.netlify/plugins/node_modules/@netlify/plugin-gatsby/src/index.js:57:26)

**Steps to reproduce**

Step-by-step instructions on how to reproduce the behavior.

Example:

1. In your Gatsby site, update your package.json start script to be `"start": "NODE_OPTIONS='-r esm' gatsby develop"`
2. Install dotenv and add an import statement for it to the top of you gatsby-config.js file `import dotenv from 'dotenv';`

**Expected behavior**

The build should complete without issue but fails as it cannot import dotenv.

**Can you submit a pull request?**

No.

Pull requests are welcome! If you would like to help us fix this bug, please
check our [contributions guidelines](../blob/master/CONTRIBUTING.md).

**Comment by ascorbic** [comment]
Hi @Sephster ,
Have you checked which node version your site is being built with, and whether it matches the one you're using locally?

**Comment by nickytonline** [comment]
Hi @Sephster, are you still having issues, or were you able to resolve this? I imagine at this point you're on a newer version of Node, probably at least v. 14?

**Comment by DamageSami** [comment]
Hi, I just googled myself here. I have almost the same issue; I installed this plugin from Netlify UI, and the build fails on the same error, I am too using ES Modules instead of CommonJS.

Netlify is building the site with node v16.15.1. On my local dev setup I am using v16.13.2.

**Comment by ascorbic** [comment]
Hi @DamageSami 
Does it work when you build locally? What is your build command?

**Comment by DamageSami** [comment]
@ascorbic Yes, it works (but the plugin is not even used in a local build).

My build command:

`"build": "cross-env NODE_OPTIONS=\"-r esm\" gatsby build --log-pages",`

**Comment by ascorbic** [comment]
Is your build command in Netlify `npm run build` or is it `gatsby build`?

**Comment by DamageSami** [comment]
@ascorbic it is `yarn build`

**Comment by ascorbic** [comment]
Can you try running it locally using the netlify CLI please?

**Comment by DamageSami** [comment]
I just ran `netlify build`. In my netlify.toml I have

```
[[plugins]]
  package = "@netlify/plugin-gatsby"
```

And the output is

```
❯ Installing plugins
   - @netlify/plugin-gatsby@1.0.3
​
❯ Loading plugins
   - @netlify/plugin-gatsby@1.0.3 from netlify.toml
​
❯ Outdated plugins
   - @netlify/plugin-gatsby@1.0.3: latest version is 3.2.4
     Migration guide: https://ntl.fyi/gatsby-plugin-migration
     To upgrade this plugin, please remove it from "netlify.toml" and install it from the Netlify plugins directory instead (https://app.netlify.com/plugins)
​
────────────────────────────────────────────────────────────────
  1. @netlify/plugin-gatsby (onPreBuild event)                  
────────────────────────────────────────────────────────────────
​
No Gatsby cache found. Building fresh.
​
────────────────────────────────────────────────────────────────
  Plugin "@netlify/plugin-gatsby" failed                        
────────────────────────────────────────────────────────────────
​
  Error message
  /(MyProjectLocation)/gatsby/gatsby-config.js:1
  import dotenv from 'dotenv'
  ^^^^^^
​
  SyntaxError: Cannot use import statement outside a module
​
  Plugin details
  Package:        @netlify/plugin-gatsby
  Version:        1.0.3
  Repository:     git+https://github.com/netlify/netlify-plugin-gatsby.git
  npm link:       https://www.npmjs.com/package/@netlify/plugin-gatsby
  Report issues:  https://github.com/netlify/netlify-plugin-gatsby/issues
​
  Error location
  In "onPreBuild" event in "@netlify/plugin-gatsby" from netlify.toml
      at loadGatsbyFile (/.netlify/plugins/node_modules/@netlify/plugin-gatsby/src/index.js:32:12)
      at onPreBuild (/.netlify/plugins/node_modules/@netlify/plugin-gatsby/src/index.js:57:26)
```

**Comment by ascorbic** [comment]
Oh, that is a very old version of the plugin. Are you able to upgrade? Are you using Gatsby 4?

**Comment by DamageSami** [comment]
Using Gatsby v3. I just followed the plugin installation instructions and added it to my netlify.toml, is there some other way to upgrade it?

**Comment by 1-800-jono** [comment]
I have the same issue. Same error message.

**Comment by nickytonline** [comment]
Awesome! Glad to hear @Sephster.
